IPL 2025 Data Pre Processing

Converting all JSON files to CSV files and making relationships between the data's.

In [2]:
import pandas as pd
import json

1.Team Match Result Pre Processing

In [3]:
with open('ipl_2025_json_files/ipl_2025_team_match_results.json') as f:
    data = json.load(f)

df_match = pd.DataFrame(data)
df_match.head()

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,Punjab Kings,RCB,RCB,6 runs,Ahmedabad,"Jun 3, 2025",Twenty20
1,MI,Punjab Kings,Punjab Kings,5 wickets,Ahmedabad,"Jun 1, 2025",Twenty20
2,GT,MI,MI,20 runs,New Chandigarh,"May 30, 2025",Twenty20
3,Punjab Kings,RCB,RCB,8 wickets,New Chandigarh,"May 29, 2025",Twenty20
4,LSG,RCB,RCB,6 wickets,Lucknow,"May 27, 2025",Twenty20

In [4]:
df_match.replace('Punjab Kings', 'PKBS', inplace = True)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date Scorecard
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025  Twenty20
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025  Twenty20
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025  Twenty20
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025  Twenty20
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025  Twenty20

In [5]:
num = 74
for index, row in df_match.iterrows():
    df_match.at[index, 'Scorecard'] = num
    num -= 1
df_match.rename({'Scorecard': 'Match Number'}, axis = 1, inplace = True)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date Match Number
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025           74
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025           73
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025           72
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025           71
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025           70

In [6]:
df_match['Match Number'] = df_match['Match Number'].astype(int)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date  Match Number
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025            74
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025            73
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025            72
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025            71
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025            70

In [7]:
df_match.to_csv('ipl_2025_csv_files/match_results_ipl_2025.csv', index = False)

2.Batting Summary Pre Processing

In [11]:
with open('ipl_2025_json_files/ipl_2025_batting_summary.json') as f:
    data = json.load(f)

df_bat = pd.DataFrame(data)
df_bat.head(25)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,c Iyer b Jamieson,16,9,2,1,177.77
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,c & b Azmatullah Omarzai,43,35,3,0,122.85
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,c Arshdeep Singh b Chahal,24,18,2,1,133.33
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),lbw b Jamieson,26,16,1,2,162.50
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,lbw b Jamieson,25,15,0,2,166.66
5,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,6,Jitesh Sharmaâ€,b Vyshak,24,10,2,2,240.00
6,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,7,Romario Shepherd,lbw b Arshdeep Singh,17,9,1,1,188.88
7,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,8,Krunal Pandya,c Iyer b Arshdeep Singh,4,5,0,0,80.00
8,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,9,Bhuvneshwar Kumar,c Arya b Arshdeep Singh,1,2,0,0,50.00
9,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,10,Yash Dayal,NaN,1,1,0,0,100.00
10,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,1,Priyansh Arya,c Salt b Hazlewood,24,19,4,0,126.31
11,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,2,Prabhsimran Singh,c Kumar b Pandya,26,22,0,2,118.18
12,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,3,Josh Inglisâ€,c Livingstone b Pandya,39,23,1,4,169.56
13,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,4,Shreyas Iyer(c),c â€ Sharma b Shepherd,1,2,0,0,50.00
14,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,5,Nehal Wadhera,c Pandya b Kumar,15,18,0,1,83.33
15,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,6,Shashank Singh,NaN,61,30,3,6,203.33
16,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,7,Marcus Stoinis,c Yash Dayal b Kumar,6,2,0,1,300.00
17,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,8,Azmatullah Omarzai,c sub (MS Bhandage) b Yash Dayal,1,2,0,0,50.00
18,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,9,Kyle Jamieson,NaN,0,2,0,0,0.00
19,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,1,Rohit Sharma,c Vyshak b Stoinis,8,7,1,0,114.28
20,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,2,Jonny Bairstowâ€,c â€ Inglis b Vyshak,38,24,3,2,158.33
21,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,3,Tilak Varma,c Arya b Jamieson,44,29,2,2,151.72
22,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,4,Suryakumar Yadav,c Wadhera b Chahal,44,26,4,3,169.23
23,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,5,Hardik Pandya(c),c â€ Inglis b Azmatullah Omarzai,15,13,1,0,115.38
24,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,6,Naman Dhir,c Stoinis b Azmatullah Omarzai,37,18,7,0,205.55

In [12]:
df_bat['out/not_out'] = df_bat.dismissal.apply(lambda x: "out" if len(x)>0 else "not_out")
df_bat.head(11)

TypeError: object of type 'float' has no len()