IPL 2025 Data Pre Processing

Converting all JSON files to CSV files and making relationships between the data's.

In [185]:
import pandas as pd
import json
import re

1.Team Match Result Pre Processing

In [186]:
with open('ipl_2025_json_files/ipl_2025_team_match_results.json') as f:
    data = json.load(f)

df_match = pd.DataFrame(data)
df_match.head()

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,Punjab Kings,RCB,RCB,6 runs,Ahmedabad,"Jun 3, 2025",Twenty20
1,MI,Punjab Kings,Punjab Kings,5 wickets,Ahmedabad,"Jun 1, 2025",Twenty20
2,GT,MI,MI,20 runs,New Chandigarh,"May 30, 2025",Twenty20
3,Punjab Kings,RCB,RCB,8 wickets,New Chandigarh,"May 29, 2025",Twenty20
4,LSG,RCB,RCB,6 wickets,Lucknow,"May 27, 2025",Twenty20

In [187]:
df_match.replace('Punjab Kings', 'PKBS', inplace = True)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date Scorecard
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025  Twenty20
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025  Twenty20
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025  Twenty20
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025  Twenty20
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025  Twenty20

In [188]:
num = len(df_match)
for index,row in df_match.iterrows():
    df_match.at[index, 'Scorecard'] = num
    num -= 1
df_match.rename({'Scorecard': 'Match Number'}, axis = 1, inplace = True)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date Match Number
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025           74
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025           73
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025           72
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025           71
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025           70

In [189]:
df_match['Match Number'] = df_match['Match Number'].astype(int)
df_match.head()

  Team 1 Team 2 Winner     Margin          Ground    Match Date  Match Number
0   PKBS    RCB    RCB     6 runs       Ahmedabad   Jun 3, 2025            74
1     MI   PKBS   PKBS  5 wickets       Ahmedabad   Jun 1, 2025            73
2     GT     MI     MI    20 runs  New Chandigarh  May 30, 2025            72
3   PKBS    RCB    RCB  8 wickets  New Chandigarh  May 29, 2025            71
4    LSG    RCB    RCB  6 wickets         Lucknow  May 27, 2025            70

In [190]:
df_match.to_csv('ipl_2025_csv_files/match_results_ipl_2025.csv', index = False)

2.Batting Summary Pre Processing

In [191]:
with open('ipl_2025_json_files/ipl_2025_batting_summary.json') as f:
    data = json.load(f)

df_bat = pd.DataFrame(data)
df_bat.head()
df_bat.shape

(1135, 10)

In [192]:
df_bat['dismissal'] = df_bat['dismissal'].fillna('')
df_bat['out/not out'] = df_bat['dismissal'].apply(lambda x: "out" if len(x) > 0 else "not out")
df_bat.head(20)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not out
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,c Iyer b Jamieson,16,9,2,1,177.77,out
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,c & b Azmatullah Omarzai,43,35,3,0,122.85,out
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,c Arshdeep Singh b Chahal,24,18,2,1,133.33,out
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),lbw b Jamieson,26,16,1,2,162.50,out
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,lbw b Jamieson,25,15,0,2,166.66,out
5,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,6,Jitesh Sharmaâ€,b Vyshak,24,10,2,2,240.00,out
6,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,7,Romario Shepherd,lbw b Arshdeep Singh,17,9,1,1,188.88,out
7,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,8,Krunal Pandya,c Iyer b Arshdeep Singh,4,5,0,0,80.00,out
8,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,9,Bhuvneshwar Kumar,c Arya b Arshdeep Singh,1,2,0,0,50.00,out
9,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,10,Yash Dayal,,1,1,0,0,100.00,not out
10,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,1,Priyansh Arya,c Salt b Hazlewood,24,19,4,0,126.31,out
11,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,2,Prabhsimran Singh,c Kumar b Pandya,26,22,0,2,118.18,out
12,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,3,Josh Inglisâ€,c Livingstone b Pandya,39,23,1,4,169.56,out
13,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,4,Shreyas Iyer(c),c â€ Sharma b Shepherd,1,2,0,0,50.00,out
14,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,5,Nehal Wadhera,c Pandya b Kumar,15,18,0,1,83.33,out
15,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,6,Shashank Singh,,61,30,3,6,203.33,not out
16,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,7,Marcus Stoinis,c Yash Dayal b Kumar,6,2,0,1,300.00,out
17,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,8,Azmatullah Omarzai,c sub (MS Bhandage) b Yash Dayal,1,2,0,0,50.00,out
18,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,9,Kyle Jamieson,,0,2,0,0,0.00,not out
19,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,1,Rohit Sharma,c Vyshak b Stoinis,8,7,1,0,114.28,out

In [193]:
df_bat['batsmanName'] = df_bat['batsmanName'].apply(lambda x: x.replace('â€', ''))
df_bat['batsmanName'] = df_bat['batsmanName'].apply(lambda x: x.replace('\xa0', ''))
df_bat.head(20)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not out
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,c Iyer b Jamieson,16,9,2,1,177.77,out
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,c & b Azmatullah Omarzai,43,35,3,0,122.85,out
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,c Arshdeep Singh b Chahal,24,18,2,1,133.33,out
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),lbw b Jamieson,26,16,1,2,162.50,out
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,lbw b Jamieson,25,15,0,2,166.66,out
5,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,6,Jitesh Sharma,b Vyshak,24,10,2,2,240.00,out
6,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,7,Romario Shepherd,lbw b Arshdeep Singh,17,9,1,1,188.88,out
7,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,8,Krunal Pandya,c Iyer b Arshdeep Singh,4,5,0,0,80.00,out
8,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,9,Bhuvneshwar Kumar,c Arya b Arshdeep Singh,1,2,0,0,50.00,out
9,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,10,Yash Dayal,,1,1,0,0,100.00,not out
10,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,1,Priyansh Arya,c Salt b Hazlewood,24,19,4,0,126.31,out
11,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,2,Prabhsimran Singh,c Kumar b Pandya,26,22,0,2,118.18,out
12,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,3,Josh Inglis,c Livingstone b Pandya,39,23,1,4,169.56,out
13,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,4,Shreyas Iyer(c),c â€ Sharma b Shepherd,1,2,0,0,50.00,out
14,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,5,Nehal Wadhera,c Pandya b Kumar,15,18,0,1,83.33,out
15,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,6,Shashank Singh,,61,30,3,6,203.33,not out
16,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,7,Marcus Stoinis,c Yash Dayal b Kumar,6,2,0,1,300.00,out
17,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,8,Azmatullah Omarzai,c sub (MS Bhandage) b Yash Dayal,1,2,0,0,50.00,out
18,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,9,Kyle Jamieson,,0,2,0,0,0.00,not out
19,"MI vs PBKS Cricket Scorecard, Qualifier 2 at A...",Mumbai Indians,1,Rohit Sharma,c Vyshak b Stoinis,8,7,1,0,114.28,out

In [194]:
df_bat.drop(columns=['dismissal'],inplace=True)
df_bat.head()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not out
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,16,9,2,1,177.77,out
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,43,35,3,0,122.85,out
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,24,18,2,1,133.33,out
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),26,16,1,2,162.50,out
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,25,15,0,2,166.66,out

In [195]:
num = len(df_match)

for index, row in df_bat.iterrows():
    match_str = row['match']
    # Assign match numbers for playoffs
    if 'Final' in match_str:
        df_bat.at[index, 'Match Number'] = num
    elif 'Qualifier 2' in match_str:
        df_bat.at[index, 'Match Number'] = num - 1
    elif 'Eliminator' in match_str:
        df_bat.at[index, 'Match Number'] = num - 2
    elif 'Qualifier 1' in match_str:
        df_bat.at[index, 'Match Number'] =num - 3
    else:
        # For league matches like '70th Match', extract the number
        match_num = re.search(r'(\d+)(?=.. Match)', match_str)
        if match_num:
            df_bat.at[index, 'Match Number'] = int(match_num.group(1))
df_bat.head(1100)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not out,Match Number
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,16,9,2,1,177.77,out,74.0
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,43,35,3,0,122.85,out,74.0
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,24,18,2,1,133.33,out,74.0
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),26,16,1,2,162.50,out,74.0
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,25,15,0,2,166.66,out,74.0
...,...,...,...,...,...,...,...,...,...,...,...
1095,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Mumbai Indians,11,Satyanarayana Raju,1,1,0,0,100.00,not out,3.0
1096,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,1,Rachin Ravindra,65,45,2,4,144.44,not out,3.0
1097,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,2,Rahul Tripathi,2,3,0,0,66.66,out,3.0
1098,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,3,Ruturaj Gaikwad(c),53,26,6,3,203.84,out,3.0
1099,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,4,Shivam Dube,9,7,0,1,128.57,out,3.0

In [196]:
df_bat['Match Number'] = df_bat['Match Number'].astype(int)
df_bat.head(1100)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not out,Match Number
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,1,Phil Salt,16,9,2,1,177.77,out,74
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,2,Virat Kohli,43,35,3,0,122.85,out,74
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,3,Mayank Agarwal,24,18,2,1,133.33,out,74
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,4,Rajat Patidar(c),26,16,1,2,162.50,out,74
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Royal Challengers Bengaluru,5,Liam Livingstone,25,15,0,2,166.66,out,74
...,...,...,...,...,...,...,...,...,...,...,...
1095,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Mumbai Indians,11,Satyanarayana Raju,1,1,0,0,100.00,not out,3
1096,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,1,Rachin Ravindra,65,45,2,4,144.44,not out,3
1097,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,2,Rahul Tripathi,2,3,0,0,66.66,out,3
1098,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,3,Ruturaj Gaikwad(c),53,26,6,3,203.84,out,3
1099,"CSK vs MI Cricket Scorecard, 3rd Match at Chen...",Chennai Super Kings,4,Shivam Dube,9,7,0,1,128.57,out,3

In [197]:
df_bat.to_csv('ipl_2025_csv_files/batting_summary_ipl_2025.csv', index = False)

3.Bowling Summary Pre Processing

In [198]:
with open ('ipl_2025_json_files/ipl_2025_bowling_summary.json') as f:
    data=json.load(f)
df_bowl=pd.DataFrame(data)
df_bowl.head()
df_bowl.shape

(862, 13)

In [199]:
num = len(df_match)

for index, row in df_bowl.iterrows():
    match_str = row['match']
    # Assign match numbers for playoffs
    if 'Final' in match_str:
        df_bowl.at[index, 'Match Number'] = num
    elif 'Qualifier 2' in match_str:
        df_bowl.at[index, 'Match Number'] = num - 1
    elif 'Eliminator' in match_str:
        df_bowl.at[index, 'Match Number'] = num - 2
    elif 'Qualifier 1' in match_str:
        df_bowl.at[index, 'Match Number'] =num - 3
    else:
        # For league matches like '70th Match', extract the number
        match_num = re.search(r'(\d+)(?=.. Match)', match_str)
        if match_num:
            df_bowl.at[index, 'Match Number'] = int(match_num.group(1))
df_bowl.head(500)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,Match Number
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Arshdeep Singh,4,0,40,3,10.00,8,3,2,2,0,74.0
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Kyle Jamieson,4,0,48,3,12.00,9,3,4,3,0,74.0
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Azmatullah Omarzai,4,0,35,1,8.75,3,2,1,2,0,74.0
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Vijaykumar Vyshak,4,0,30,1,7.50,5,2,0,2,0,74.0
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Yuzvendra Chahal,4,0,37,1,9.25,3,1,2,0,0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Anrich Nortje,3,0,23,1,7.66,10,5,0,0,0,31.0
496,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Harshit Rana,3,0,25,3,8.33,13,1,3,2,0,31.0
497,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Varun Chakravarthy,4,0,21,2,5.25,10,0,1,0,0,31.0
498,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Sunil Narine,3,0,14,2,4.66,9,1,0,1,0,31.0
499,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Punjab Kings,Marco Jansen,3.1,0,17,3,5.36,12,3,0,0,0,31.0

In [200]:
df_bowl['Match Number']=df_bowl['Match Number'].astype(int)
df_bowl.head(500)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,Match Number
0,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Arshdeep Singh,4,0,40,3,10.00,8,3,2,2,0,74
1,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Kyle Jamieson,4,0,48,3,12.00,9,3,4,3,0,74
2,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Azmatullah Omarzai,4,0,35,1,8.75,3,2,1,2,0,74
3,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Vijaykumar Vyshak,4,0,30,1,7.50,5,2,0,2,0,74
4,"PBKS vs RCB Cricket Scorecard, Final at Ahmeda...",Punjab Kings,Yuzvendra Chahal,4,0,37,1,9.25,3,1,2,0,0,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Anrich Nortje,3,0,23,1,7.66,10,5,0,0,0,31
496,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Harshit Rana,3,0,25,3,8.33,13,1,3,2,0,31
497,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Varun Chakravarthy,4,0,21,2,5.25,10,0,1,0,0,31
498,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Kolkata Knight Riders,Sunil Narine,3,0,14,2,4.66,9,1,0,1,0,31
499,"PBKS vs KKR Cricket Scorecard, 31st Match at N...",Punjab Kings,Marco Jansen,3.1,0,17,3,5.36,12,3,0,0,0,31

In [201]:
df_bowl.to_csv('ipl_2025_csv_files/bowling_summary_ipl_2025.csv',index=False)